bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>', views.add_to_bag, name='add_to_bag'), 
    path('remove/<item_id>/', views.remove_bag_item, name='remove_bag_item'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_details, name='product_details'),
    path('add', views.add_product, name='add_product')
]

vibehouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from products.models import Products
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2,
                                        null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False,
                                  default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            sdp = settings.STANDARD_DELIVERY_PERCENTAGE
            self.delivery_cost = self.order_total * sdp / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(Products, null=False, blank=False,
                                on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True,
                                    blank=True)  # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, blank=False,
                                         editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    
    class Meta:
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=100)
    frontend_name = models.CharField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return self.name
    
    def get_frontend_name(self):
        return self.frontend_name
    
    
class Products(models.Model):
    class Meta:
        verbose_name_plural = 'Products'
        
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=300)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1200, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    sku = models.CharField(max_length=30, null=True, blank=True)
    collection = models.CharField(max_length=70, null=True, blank=True)
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    
    
    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Products, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Products
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_frontend_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Products, Category
from .forms import ProductForm

# Create your views here.

def all_products(request):
    """ A view to show all products, including sorting and search queries """

    products = Products.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_nameLower('name'))
                # the below allows to sort by name rather than id so its more user friendly
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)
            
            
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

            
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Ooops! Looks like you didn't enter anything.")
                return redirect('products')
            
            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)


    sorting_by = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories' : categories,
        'sorting_by': sorting_by,
    }

    return render(request, 'products/products.html', context)


def product_details(request, product_id):
    # a view that shows individual product detail 
    product = get_object_or_404(Products, pk=product_id)
    
    context = {
        'product' : product,
    }
    
    return render(request, 'products/product_details.html', context)


def add_product(request):
    """ Add a product to the store """
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('add_product'))
        else:
            messages.error(request, 'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()
        
    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

products/templates/products/product_details.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container">
    <div class="row">
        <div class="col">
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<!-- Page item Area -->
<div id="page_item_area">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 text-left">
                <h3>Item Details</h3>
            </div>		

            <div class="col-sm-6 text-right">
                <ul class="p_items">
                    <li><a href="{% url 'home' %}">home</a></li>
                    {% if product.category %}
                    <li><a href="{% url 'products' %}?category={{ product.category.name }}">{{ product.category }}</a></li>
                    {% endif %}
                    <li><span>{{ product.name }}</span></li>
                </ul>					
            </div>	
                
        
            
        </div>
    </div>
</div>

<!-- Product Details Area  -->
<div class="prdct_dtls_page_area">
    <div class="container">
        <div class="row">
            <!-- Product Details Image -->
            <div class="col-md-6 col-xs-12">
                <div class="pd_img fix">
                    {% if product.image %}
                    <a href="{% url 'product_details' product.id %}">
                    <img class="detail_img img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}"/>
                    </a>
                    {% else %}
                    <a href="{% url 'product_details' product.id %}">
                    <img src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}"/>
                    </a>
                    {% endif %}
                </div>
            </div>
            <!-- Product Details Content -->
            <div class="col-md-6 col-xs-12">
                <div class="prdct_dtls_content">
                    <a class="pd_title" href="#">{{ product.name }}</a>
                    <div class="pd_price_dtls fix">
                        <!-- Product Price -->
                        <div class="pd_price">
                            <span class="new">£{{ product.price }}</span>
                        </div>
                        <!-- Product Rating -->
                        <div class="pd_ratng">
                            <div class="rtngs">
                                {% if product.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Ratings Yet</small>
                    {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="pd_text">
                        <h4>overview:</h4>
                        <p>{{ product.description }}</p>
                        {% if product.category %}
                                               <small> <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                                                    <i class="fas fa-tag mr-1"></i>{{ product.category.name }}
                                                </a> </small> <br>
                                            {% endif %}
                    </div>
                    <form class="form form-check" action="{% url 'add_to_bag' product.id %}" method="POST">
                        {% csrf_token %}
                    <div class="pd_img_size fix">
                        {% with product.has_sizes as sizes %}
                        {% if sizes %}
                        <h4>size:</h4>
                        <div class="" data-toggle="">
                            <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                <option value="xs">XS</option>
                                <option value="s">S</option>
                                <option value="m" selected>M</option>
                                <option value="l">L</option>
                                <option value="xl">XL</option>
                            </select>
                          </div>
                        {% endif %}
                    </div>
                    
                        
                    <div class="col-12">
                        <p class="mt-3"><strong>Quantity:</strong></p>
                        <div class="form-group w-50">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <button class="decrement-qty btn btn-black rounded-0" 
                                        data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                        <span class="icon">
                                            <i class="fas fa-minus"></i>
                                        </span>
                                    </button>
                                </div>
                                <input class="form-control qty_input" type="number"
                                    name="quantity" value="1" min="1" max="99"
                                    data-item_id="{{ product.id }}"
                                    id="id_qty_{{ product.id }}">
                                <div class="input-group-append">
                                    <button class="increment-qty btn btn-black rounded-0"
                                        data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                        <span class="icon">
                                            <i class="fas fa-plus"></i>
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
               
                    <!-- Product Action -->
                    <div class="pd_btn fix bag_btn">
                        <input class="btn btn-default acc_btn btn_icn" type="submit" value="Add to Bag">
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        {% endwith %}
                    </div>
                    
                </form>

    
    

    
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container">
    <div class="row">
        <div class="col">
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
	<!-- Page item Area -->
    <div id="page_item_area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 text-left">
                    <h3>Shop</h3>
                </div>		

                <div class="col-sm-6 text-right">
                    <ul class="p_items">
                        <li><a href="{% url 'home' %}">home</a></li>
                        {% if product.category %}
                        <li><a href="{% url 'products' %}?category={{ product.category.name }}">{{ product.category }}</a></li>
                        {% endif %}
                        <li><span>{{ product.name }}</span></li>
                    </ul>					
                </div>	
            </div>
        </div>
    </div>
    
    <!-- Shop Product Area -->
    <div class="shop_page_area">
        <div class="container">
            <div class="shop_bar_tp fix">
                <div class="row">
                    <div class="col-sm-6 col-xs-12 short_by_area">
                        <div class="short_by_inner">
                            <label></label>
                            <select class="show-select">
                             
                            </select>
                        </div>


                    <div class="col-sm-6 col-xs-12 show_area">
                        <div class="show_inner">
                            <label>Sort:</label>
                            <select id="sort-selector" class="show-select">
                                <option value="reset" {% if sorting_by == 'None_None' %}selected{% endif %}>Sort</option>
                                <option value="price_asc" {% if sorting_by == 'price_asc' %}selected{% endif %}>Price Low to High</option>
                                <option value="price_desc" {% if sorting_by == 'price_desc' %}selected{% endif %}>Price High to Low</option>
                                <option value="rating_desc" {% if sorting_by == 'rating_desc' %}selected{% endif %}>Rating High to Low</option>
                                <option value="rating_asc" {% if sorting_by == 'rating_asc' %}selected{% endif %}>Rating Low to High</option>
                                <option value="category_asc" {% if sorting_by == 'category_asc' %}selected{% endif %}>Category A-Z</option>
                                <option value="category_desc" {% if sorting_by == 'category_desc' %}selected{% endif %}>Category Z-A</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 order-md-first">
                    <p class="text-muted mt-3 text-center text-md-left">
                        {% if search_term or current_categories or sorting_by != 'None_None' %} 
                        <span class="small"><a href="{% url 'products' %}"> Products Home</a> </span>
                        {% endif %}
                        {{ products|length }} Products{% if search_term %} found for <strong>"{{ search_term }}"</strong> 
                        {% endif %}
                    </p>
                </div>
            </div>	
                
            <div class="shop_details text-center">
                <div class="row">					
                    {% for product in products %}
                    <div class="col-md-3 col-sm-6">
                        <div class="single_product">
                            
                            <div class="product_image">
                                {% if product.image %}
                                <a href="{% url 'product_details' product.id %}">
                                <img src="{{ product.image.url }}" alt="{{ product.name }}"/>
                                </a>
                                {% else %}
                                <a href="{% url 'product_details' product.id %}">
                                <img src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}"/>
                                </a>
                                {% endif %}
                                <div class="box-content">
                                    <a href="#"><i class="fa fa-heart-o"></i></a>
                                    <a href="#"><i class="fa fa-cart-plus"></i></a>
                                    <a href="#"><i class="fa fa-search"></i></a>
                                </div>										
                            </div>
                            <div class="product_btm_text">
                                <p>
                                <h4><a href="#">{{ product.name }}</a></h4> <br>
                                {% if product.rating %}
                                <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating}} / 5 </small> <br>
                                {% else %}
                                <small class="text-muted">No Ratings Yet</small> <br>
                                {% endif %}
                                {% if product.category %}
                                               <small> <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                                                    <i class="fas fa-tag mr-1"></i>{{ product.category.name }}
                                                </a> </small> <br>
                                            {% endif %}
                                <span class="price">£{{ product.price }}</span>
                                
                                </p>
                            </div> 
                        </div>								
                    </div> <!-- End Col -->			
                    {% endfor %}	


    <!--  FOOTER START  -->
    <footer class="bg-light text-center text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2022 Copyright:
          <a class="text-dark" href="">K Ellis </a>
        </div>
        <!-- Copyright -->
      </footer>

{% endblock %}

{% block postloadjs%}

<script type="text/javascript">
    $('#sort-selector').change(function() {
        var selector = $(this);
        var currentUrl = new URL(window.location);

        var selectedVal = selector.val();
        if(selectedVal != "reset"){
            var sort = selectedVal.split("_")[0];
            var direction = selectedVal.split("_")[1];

            currentUrl.searchParams.set("sort", sort);
            currentUrl.searchParams.set("direction", direction);

            window.location.replace(currentUrl);
        } else {
            currentUrl.searchParams.set("sort");
            currentUrl.searchParams.set("direction");

            window.location.replace(currentUrl);
        }
    })
    </script>
    {% endblock %}